app/accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from .forms import LoginForm 

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', redirect_authenticated_user=True, authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html', next_page='accounts:login'), name='logout'),
] 

app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import handler404

handler404 = 'storage.views.custom_404'

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('request.urls')),
    path('accounts/', include('accounts.urls')),
    path('storage/', include('storage.urls')),
    path('return/', include('return.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/layouts/partials/header.html
<nav class="navbar navbar-expand-lg bg-bo-tertiary">
  <div class="container-fluid">
    <!--<a class="navbar-brand" href="#">Navbar</a>!-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menu" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="menu">
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active text-white" aria-current="page" href="{% url 'storage:all_equipments' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active text-white" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link active text-white" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active text-white" href="{% url 'accounts:register' %}">Signup</a>
            </li>
        {% endif %}
      </ul>
    </div>
    <div>
      <span class="text-white"> {{ request.user.username }} </span>
    </div>
  </div>
</nav>