app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import handler404

handler404 = 'storage.views.custom_404'

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('request.urls')),
    path('accounts/', include('accounts.urls')),
    path('storage/', include('storage.urls')),
    path('return/', include('return.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/request/urls.py
from django.urls import path

from . import views

app_name = 'request'

urlpatterns = [
    path('', views.index, name='index'),
    path('warehouse/', views.warehouse, name='warehouse'),
    path('details/<int:id>/', views.details_request, name='details_request'),
    path('new request', views.new_request, name='new_request'),
    path('update request/<int:id>/', views.update_request, name='update_request'),
    path('search request/', views.search_request, name='search_request'),
]

app/request/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class Requete(models.Model):
    staff_name = models.CharField(max_length=100)
    department = models.CharField(max_length=30, choices=[
        ("rh", "HR"),
        ("technique", "Network"),
        ("sales", "Commercial & Marketing"),
        ("finance", "Finance"),
    ], default='sales')
    project_code = models.CharField()
    type_service = models.CharField(max_length=20, choices=[
        ("installation", "Installation"),
        ("service_repair", "Service/Repair"),
        ("transfer", "Transfer"),
        ("sale", "Sale"),
    ], default='installation')
    customer = models.CharField()
    location = models.CharField()
    date_de_creation = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    manager_signature = models.CharField (max_length=50, choices=[
        ("test", "Test"),
        ], default='test')
    line_manager_name = models.CharField (max_length=50, choices=[
        ("test", "Test"),
        ], default='test')
    items_recieved_name = models.CharField (max_length=50)
    items_recieved_signature = models.CharField (max_length=50)
    issued_name = models.CharField (max_length=50, choices=[
        ("test", "Test"),
        ], default='test')
    issued_signature = models.DateTimeField(auto_now_add=True)
   # supplier = models.CharField(max_length=50)
    status = models.CharField(max_length=30, choices=[
        ("v", "valide"),
        ("n", "non valide"),
    ], default='n')
    delivery = models.CharField(max_length=30, choices=[
        ("y", "yes"),
        ("n", "no"),
    ], default='n')
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=True)
    
    def __str__(self):
        return self.project_code

app/request/forms.py
from django import forms

from .models import Requete

class RequeteForm(forms.ModelForm):
    staff_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    
    choix_d = [("rh", "HR"), ("technique", "Network"), ("sales", "Commercial & Marketing"), ("finance", "Finance")]
    department = forms.ChoiceField(choices = choix_d)
    
    project_code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    
    choix_t = [("installation", "Installation"), ("service_repair", "Service/Repair"), ("transfer", "Transfer"), ("sale", "Sale")]
    type_service = forms.ChoiceField(choices = choix_t, widget = forms.RadioSelect)
    
    customer = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    location = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    
    choix_m = [("test", "Test")]
    manager_signature = forms.ChoiceField(choices = choix_m)
    
    choix_l = [("test", "Test")]
    line_manager_name = forms.ChoiceField(choices = choix_l)
    
    items_recieved_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    items_recieved_signature = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    
    choix_i = [("test", "Test")]
    issued_name = forms.ChoiceField(choices = choix_i)
    
    class Meta:
        model = Requete
        fields = ('staff_name', 'department', 'project_code', 'type_service', 'customer', 'location', 
                  'manager_signature', 'line_manager_name', 'items_recieved_name', 'items_recieved_signature', 'issued_name')           

app/request/views.py
from django.shortcuts import render, redirect

from .models import Requete

from .forms import RequeteForm

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from django.http import Http404, HttpResponseRedirect

from django.db.models import Q

from django.core.paginator import Paginator

# Create your views here.

@login_required
def index(request):
    user = request.user     
    demandes_user = Requete.objects.filter(user=user).order_by('id') 
    
    context = {
        'demandes' : demandes_user
    }
    
    return render(request, 'index.html', context)


@login_required
def warehouse(request):
    demandes = Requete.objects.all()
    demande_number = demandes.count()
    paginator = Paginator(demandes, 4)
    
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)
    
    message = f'{demande_number} Requêtes :'
        
    if demande_number == 1:
        message = f'{demande_number} Requête :'
    context = {
        'demandes': page_object,
        'message': message,
    }
    
    return render(request, 'warehouse.html', context)


@login_required
def details_request(request, id):
    details = Requete.objects.get(id=id)
    equipments = request.GET.get('equipment')
        
    context = {
        'details': details,
        'equipments': equipments,
    }
    
    return render(request, 'details_request.html', context)


@login_required
def new_request(request):
    
    if request.method =='POST':
        form = RequeteForm(request.POST)
        if form.is_valid(): 
            form = form.save(commit=False)
            form.user = request.user
            form.save()            
            return redirect('request:index')
        
    else:
        form = RequeteForm()
        
    context = {
        'form': form,
    }

    return render(request, 'new_request.html', context)


@login_required
def update_request(request, id):
    demande = Requete.objects.get(id=id)
    
    if demande.user == request.user:
        if request.method == 'POST':
            form = RequeteForm(request.POST, instance=demande)
            if form.is_valid():
                form.save()
                return redirect('request:index')
                
        else:
            form = RequeteForm(instance=demande)
    else:
        raise Http404
    
    context = {
        'form':form
    }
    return render(request, 'update_request.html', context)


@login_required
def search_request(request):
    search = request.GET.get('search')
    demandes = Requete.objects.filter(Q(project_code__icontains=search) |
                                      Q(staff_name__icontains=search))
    demande_number = demandes.count()
    
    message = f'{demande_number} Results :'
    
    if demande_number == 1:
        message = f'{demande_number} Result :'
        
    context = {
        'demandes': demandes,
        'message': message,
    }
    
    return render(request, 'search_request.html', context)

app/request/templates/details_request.html
{% extends 'requetes/layouts/base.html' %}

{% block title %} Request details {% endblock %}
 
{% block body %}
<div class="container">
    <h6 class="display-6 text-center my-3"> STORE REQUEST FORM </h6>
            <form action="" method="get">
                <div class="row mt-2 mb-3">
                    <div class="col-md-6">
                        <label class="form-label" for="name"> Date : </label> 
                        <input class="form-control" type="text" name="staff" id="staff" value="{{ details.date_de_creation }}" disabled> <br>
                        <label class="form-label" for="name"> Staff name : </label> 
                        <input class="form-control" type="text" name="staff" id="staff" value="{{ details.staff_name }}" disabled> <br>
                        <label class="form-label" for="name"> Department : </label>
                        <input class="form-control" type="text" name="staff" id="staff" value="{{ details.department }}" disabled> <br>
                        <label class="form-label" for="name"> Project Code : </label>
                        <input class="form-control" type="text" name="staff" id="staff" value="{{ details.project_code }}" disabled>
                        </div>
                    <div class="col-md-6 mt-4">
                        <ul class="list-unstyled list-inline d-flex justify-content-end">
                            <li class="list-inline-item"><input type="radio" value="{{ details.type_service }}"></li>
                            <li class="list-inline-item"><label class="radio-inline"> Installation </label></li>
                            <li class="list-inline-item"><input type="radio" value="{{ details.type_service }}"></li>
                            <li class="list-inline-item"><label class="radio-inline"> Service/Repair </label></li>
                            <li class="list-inline-item"><input type="radio" value="{{ details.type_service }}"></li>
                            <li class="list-inline-item"><label class="radio-inline"> Transfer </label></li>
                            <li class="list-inline-item"><input type="radio" value="{{ details.type_service }}"></li>
                            <li class="list-inline-item"><label class="radio-inline"> Sale </label> <br></li>
                        </ul>
                        <ul>
                            <label class="form-label" for="customer"> Customer : </label>
                            <input type="text" class="form-control" name="Customer" id="customer" value="{{ details.customer }}" disabled> <br> 
                            <label class="form-label" for="location"> Location : </label>
                            <input type="text" class="form-control" name="Location" id="location" value="{{ details.location }}" disabled> <br>        
                        </ul>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-12">
                        <table  class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Description</th>
                                    <th>Quantité</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for equipment in equipments %}
                                <tr>
                                    <td>{{ equipment }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="row mt-5">
                    <div class="col-7">
                    </div>
                    <div class="col-5">
                        <label class="form-label form-text-center" for="manager"> Manager's Signature : </label> 
                        <input type="text" class="form-control" name="Manager's Signature" id="manager" value="{{ details.manager_signature }}" disabled> <br>
                        <label class="form-label" for="line manager"> Line Manager's Name : </label> 
                        <input type="text" class="form-control" name="Line Manager's Name" id="line manager" value="{{ details.line_manager_name }}" disabled> <br>
                        <label class="form-label" for="items name"> Items Recieved by Name : </label>
                        <input type="text" class="form-control" name="Items Recieved by Name" id="items name" value="{{ details.items_recieved_name }}" disabled> <br>
                        <label class="form-label" for="items signature"> Items Recieved by Signature : </label>
                        <input type="text" class="form-control" name="Items Recieved by Signature" id="items signature" value="{{ details.items_recieved_signature }}" disabled> <br>
                        <label class="form-label" for="issued name"> Issued by Name : </label>
                        <input type="text" class="form-control" name="Issued by Name" id="issued name" value="{{ details.issued_name }}" disabled> <br>
                        <label class="form-label" for="issued signature"> Issued by Signature : </label>
                        <input type="text" class="form-control" name="Issued by Signature" id="issued signature" value="{{ details.issued_signature }}" disabled> <br>
                    </div>
                </div>
            </form>

</div>
{% endblock %}

app/request/templates/index.html
{% extends 'requetes/layouts/base.html' %}

{% block title %} page {% endblock %}
 
{% block body %}

        <div class="container">
            <div class="d-grid gap-2 d-md-flex justify-content-md-end my-3">
                <button type="button" class="btn btn-outline-primary">
                    <a class="nav-link" href="{% url 'request:new_request' %}">new</a>
                </button>
            </div>
            <h2> {{ message }} </h2>
            <br>      
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>S/N</th>
                            <th>Project Code</th>
                            <th colspan="2">Action</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for demande in demandes %}
                        <tr>
                            <td>
                                <button class="btn btn-outline-primary">
                                    {{ demande.id }}
                                </button>
                            </td>
                            <td>
                                <a class="nav-link text-primary" href="{% url 'request:details_request' demande.id %}">{{ demande.project_code }}</a>
                            </td>
                            <td>
                                <a class="nav-link" href="{% url 'request:update_request' demande.id %}">✏️</a>
                            </td>
                            <td>
                                <a class="nav-link" href="{% url 'storage:choice_equipment' %}">🛒</a>
                            </td>
                            <td>{{ demande.date_de_creation }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
{% endblock %}

app/request/templates/new_request.html
{% extends 'requetes/layouts/base.html' %}

{% block title %} New Request {% endblock %}
 
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h4 class="text-center my-2">New</h4>
                <form action="" method="post">
                    {% if form.subject.errors %}
                        {% for error in form.subject.errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}<br>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="col-12">
                        <button class="btn btn-primary" type="submit">new</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

app/request/templates/search_request.html
{% extends 'requetes/layouts/base.html' %}

{% block title %} Warehouse {% endblock %}
 
{% block body %}

        <div class="container mt-3">
            <h2> {{ message }} </h2>
            <div>
                <form action="{% url 'request:search_request' %}" method="get" class="d-flex ml-3">
                    <input type="search" name="search" class="form-control me-2" placeholder="search">
                    <button class="btn btn-outline-primary ml-2" type="submit">Search</button>
                </form>
            </div>
            <br>
            <div class="table-responsive">        
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>S/N</th>
                            <th>Project Code</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for demande in demandes %}
                        <tr>
                            <td>
                                <button class="btn btn-outline-primary">
                                    {{ demande.id }}
                                </button>
                            </td>
                            <td>
                                <a href="{% url 'request:details_request' demande.id %}">{{ demande.project_code }}</a>
                            </td>
                            <td>{{ demande.date_de_creation }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}

{% block footer %}


    <ul class="pagination justify-content-center">
        {% if demandes.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ demandes.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        <li class="page-item">
            <p class="page-link text-muted">
                Page {{ demandes.number }} of {{ demandes.paginator.num_pages }}.
            </p>
        </li>
        {% if demandes.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ demandes.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>


{% endblock %}

app/request/templates/update_request.html
{% extends 'requetes/layouts/base.html' %}

{% block title %} Update Request {% endblock %}
 
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h4 class="text-center my-2">Update</h4>
                    <form action="" method="post">
                        {% if form.subject.errors %}
                            {% for error in form.subject.errors %}
                                <p class="text-danger"><strong>{{ error }}</strong></p>
                            {% endfor %}
                        {% endif %}
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {{ field }}<br>
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <p class="text-danger"><strong>{{ error }}</strong></p>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="col-12">
                            <button class="btn btn-primary" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>    
    </div>
{% endblock body %}

app/request/templates/warehouse.html
{% extends 'requetes/layouts/base.html' %}

{% block title %} Warehouse {% endblock %}
 
{% block body %}

        <div class="container mt-3">
            <h2> {{ message }} </h2>
            <div>
                <form action="{% url 'request:search_request' %}" method="get" class="d-flex ml-3">
                    <input type="search" name="search" class="form-control me-2" placeholder="search">
                    <button class="btn btn-outline-primary ml-2" type="submit">Search</button>
                </form>
            </div>
            <br>
            <div class="table-responsive">        
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>S/N</th>
                            <th>Project Code</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for demande in demandes %}
                        <tr>
                            <td>
                                <button class="btn btn-outline-primary">
                                    {{ demande.id }}
                                </button>
                            </td>
                            <td>
                                <a class="nav-link text-primary" href="{% url 'request:details_request' demande.id %}">{{ demande.project_code }}</a>
                            </td>
                            <td>{{ demande.date_de_creation }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}

{% block footer %}


    <ul class="pagination justify-content-center">
        {% if demandes.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ demandes.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        <li class="page-item">
            <p class="page-link text-muted">
                Page {{ demandes.number }} of {{ demandes.paginator.num_pages }}.
            </p>
        </li>
        {% if demandes.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ demandes.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>


{% endblock %}